### ISSUE TITLE
Peewee's `model_to_dict` helper

### ISSUE THREAD

**Issue by coleifer** [klen/bottle-peewee#1]
Hey, I was taking a peek at your code and saw two methods:
- `def get_dictionary_from_model(model, fields=None, exclude=None):`
- `def get_model_from_dictionary(model, field_dict):`

I wanted to let you know that the `playhouse.shortcuts` extension module contains two helpers which you might be able to use instead:
- http://docs.peewee-orm.com/en/latest/peewee/playhouse.html#model_to_dict
- http://docs.peewee-orm.com/en/latest/peewee/playhouse.html#dict_to_model

**Comment by klen** [comment]
I didnt know about. I've changed the functionality. Thank you.

Also, could you please make look on https://github.com/klen/peewee_migrate? I've created it for myself because I was needed a simple migration tool for one of my projects. It's pretty simple but works for me. Your feedback could be very useful.
